device: cuda
submission_name: eval_nine_ensmbl
test_data_dir: datasets/Contest_Dataset/test/images
pred_dir_base: submissions
patch_size: 256
inference_approach: mean # union, mean, voting
mean_threshold: 0.3
resize: True
metrics:
  eps: 1.0e-7

models: [
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-bce-resnet34_only_cc_lr/checkpoints/best_model.pth,
    threshold: 0.25
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-bce-resnet50_only_cc_rop/checkpoints/best_model.pth,
    threshold: 0.25
  },
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-dice-resnet34_only_cc_lr/checkpoints/best_model.pth,
    threshold: 0.25
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-dice-resnet50_only_cc_lr/checkpoints/best_model.pth,
    threshold: 0.25
  },
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-focal-resnet34_only_cc_lr/checkpoints/best_model.pth,
    threshold: 0.25
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-focal-resnet50_only_cc_lr/checkpoints/best_model.pth,
    threshold: 0.25
  }
]
