device: cpu
submission_name: eval_ha
test_data_dir: data/test/images
pred_dir_base: submissions
patch_size: 256
inference_approach: mean # union, mean, voting
mean_threshold: 0.2
resize: True
metrics:
  eps: 1.0e-7

models: [
  # {
  #   name: unet,
  #   backbone: resnet34,
  #   ckpt_path: experiments/bce_resnet35/checkpoints/best_model.pth,
  #   threshold: 0.16
  # },
  # {
  #   name: unet,
  #   backbone: resnet34,
  #   ckpt_path: experiments/focal_resnet34/checkpoints/best_model.pth,
  #   threshold: 0.26
  # },
  # {
  #   name: unet,
  #   backbone: resnet34,
  #   ckpt_path: experiments/dice_bce_resnet34/checkpoints/best_model.pth,
  #   threshold: 0.05
  # },
  # {
  #   name: unet,
  #   backbone: resnet101,
  #   ckpt_path: experiments/bce_resnet101/checkpoints/best_model.pth,
  #   threshold: 0.16
  # },
  {
    name: unet,
    backbone: resnet34,
    ckpt_path: experiments/bce_resnet/best_model.pth,
    threshold: 0.16
  }
]

# Homography generation parameters
num_homographies: 5
homography:
  difficulty: 0.3
  translation: 1.0
  max_angle: 60
  n_angles: 10
  patch_shape: [256, 256]
  min_convexity: 0.05
