device: cuda
submission_name: eval_ha_no_pad_new_vone
test_data_dir: datasets/Contest_Dataset/test/images
pred_dir_base: submissions
patch_size: 256
inference_approach: mean # union, mean, voting
mean_threshold: 0.15
resize: True
metrics:
  eps: 1.0e-7

models: [
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-bce-resnet34_cont/checkpoints/best_model.pth,
    threshold: 0.16
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-bce-resnet50_cont/checkpoints/best_model.pth,
    threshold: 0.26
  },
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-dice-resnet34_cont/checkpoints/best_model.pth,
    threshold: 0.05
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-dice-resnet50_cont/checkpoints/best_model.pth,
    threshold: 0.05
  },
  {
    name: UnetPlusPlus,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-focal-resnet34_cont/checkpoints/best_model.pth,
    threshold: 0.16
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/new-focal-resnet50_cont/checkpoints/best_model.pth,
    threshold: 0.26
  },
  {
    name: UnetPlusPlus,
    backbone: resnet50,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/old-focal-resnet50/checkpoints/best_model.pth,
    threshold: 0.05
  }
]

# Homography generation parameters
num_homographies: 10
seed: 42
pad_value: 24
homography:
  difficulty: 0.3
  translation: 1.0
  max_angle: 60
  n_angles: 10
  patch_shape: [256,256]
  min_convexity: 0.05
