device: cpu
submission_name: eval_sixth_MLP
test_data_dir: datasets/Contest_Dataset/test/images
pred_dir_base: submissions
patch_size: 256
inference_approach: mean # union, mean, voting
mean_threshold: 0.05
resize: True
metrics:
  eps: 1.0e-7

models: [
  {
    name: unet,
    backbone: resnet34,
    ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/bce-resnet34_MLP_focal/checkpoints/best_model.pth,
    threshold: 0.37
  },
  # {
  #   name: UnetPlusPlus,
  #   backbone: resnet34,
  #   ckpt_path: /project/Temp/CIL-RoadSegmentation/experiments/bce-resnet34_basic/checkpoints/best_model.pth,
  #   threshold: 0.37
  # },
]

